version: '3.3'

services:

  logspout:
    image: micahhausler/logspout:gelf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:80
    command: gelf://{{ipint}}:12201
    depends_on:
      - graylog
    networks:
      - graylognet
    logging:
     driver: "json-file"
     options:
      max-size: "250m"
      max-file: "3"

  mongo:
    image: "mongo:{{ mongo_image_version }}"
    volumes:
      - type: {{ mongo_volume_type }}
        source: /seu_volume/graylog/data/mongo
        target: /data/db
    networks:
      - graylognet
    logging:
     driver: "json-file"
     options:
      max-size: "250m"
      max-file: "3"

  elasticsearch:
    image: "elasticsearch:{{ es_image_version }}"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - type: {{ es_volume_type }}
        source: /seu_volume/graylog/data/elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms5g -Xmx5g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 8g
    networks:
      - graylognet
    logging:
     driver: "json-file"
     options:
      max-size: "250m"
      max-file: "3"

  graylog:
    image: graylog2/server:{{ graylog_image_version }}
    volumes:
      - type: {{ graylog_volume_type }}
        source: /seu_volume/graylog/data/journal
        target: /usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: {{ graylog_password_secret }}
      GRAYLOG_ROOT_PASSWORD_SHA2: AQUI O HASH GERADO PELO COMANDO: #echo -n "SUA_SENHA" | shasum -a 256
      GRAYLOG_WEB_ENDPOINT_URI: http://{{ graylog_url }}:9000/api
      GRAYLOG_WEB_ENDPOINT_URI: http://{{ipext}}/api/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_PASSWORD_SECRET: {{graylog_pass_secret}}
      GRAYLOG_ROOT_PASSWORD_SHA2: {{graylog_root_pass}}
      GRAYLOG_OUTPUT_FLUSH_INTERVAL: 1
      GRAYLOG_INPUTBUFFER_RING_SIZE: 4096
      GRAYLOG_INPUTBUFFER_PROCESSORS: 1
      GRAYLOG_PROCESSBUFFER_PROCESSORS: 4
      GRAYLOG_OUTPUTBUFFER_PROCESSORS: 5
      GRAYLOG_PROCESSOR_WAIT_STRATEGY: blocking
      GRAYLOG_RING_SIZE: 524288
      GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: 4gb
      GRAYLOG_OUTPUT_BATCH_SIZE: 20000
      GRAYLOG_STREAM_PROCESSING_TIMEOUT: 10000
      GRAYLOG_STREAM_PROCESSING_MAX_FAULTS: 10
    ports:
      - "9000:9000"
      - "12204:12204"
      - "12205:12205"
      - "12200:12200/udp"
      - "12201:12201/udp"
    logging:
     driver: "json-file"
     options:
      max-size: "250m"
      max-file: "3"
