version: '3.3'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - type: bind
        source: /seu_volume/graylog/data/mongo
        target: /data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - type: bind
        source: /seu_volume/graylog/data/elasticsearch
        target: /usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.3.2-2
    volumes:
      - type: bind
        source: /seu_volume/graylog/data/journal
        target: /usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: LINUXtipsVAIIII123456
      GRAYLOG_ROOT_PASSWORD_SHA2: AQUI O HASH GERADO PELO COMANDO: #echo -n "SUA_SENHA" | shasum -a 256
      GRAYLOG_WEB_ENDPOINT_URI: http://SEU_IP:9000/api
    ports:
      - "9000:9000"
      - "12204:12204"
      - "12205:12205"
      - "12200:12200/udp"
      - "12201:12201/udp"
