version: '{{ compose_version }}'

services:
  mongo:
    image: "mongo:{{ mongo_image_version }}"
    volumes:
      - type: {{ mongo_volume_type }}
        source: /seu_volume/graylog/data/mongo
        target: /data/db
  elasticsearch:
    image: "elasticsearch:{{ es_image_version }}"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - type: {{ es_volume_type }}
        source: /seu_volume/graylog/data/elasticsearch
        target: /usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:{{ graylog_image_version }}
    volumes:
      - type: {{ graylog_volume_type }}
        source: /seu_volume/graylog/data/journal
        target: /usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: {{ graylog_password_secret }}
      GRAYLOG_ROOT_PASSWORD_SHA2: AQUI O HASH GERADO PELO COMANDO: #echo -n "SUA_SENHA" | shasum -a 256
      GRAYLOG_WEB_ENDPOINT_URI: http://{{ graylog_url }}:9000/api
    ports:
      - "9000:9000"
      - "12204:12204"
      - "12205:12205"
      - "12200:12200/udp"
      - "12201:12201/udp"
